//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Companies = new HashSet<Company>();
            this.Members = new HashSet<Member>();
        }
    
        public long city_id { get; set; }
        public string city_name { get; set; }
        public Nullable<long> con_id { get; set; }
        public Nullable<long> sta_id { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Member> Members { get; set; }
    }
}
