//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.users = new HashSet<user>();
            this.UserTypes = new HashSet<UserType>();
        }
    
        public long com_id { get; set; }
        public string com_name { get; set; }
        public string com_invoicename { get; set; }
        public string com_address1 { get; set; }
        public string com_address2 { get; set; }
        public string com_address3 { get; set; }
        public string com_district { get; set; }
        public Nullable<long> city_id { get; set; }
        public Nullable<long> sta_id { get; set; }
        public Nullable<long> con_id { get; set; }
        public string com_pincode { get; set; }
        public string com_mobileno { get; set; }
        public string com_website { get; set; }
        public string com_phone { get; set; }
        public string com_email { get; set; }
        public string com_tin { get; set; }
        public string com_cst { get; set; }
        public System.DateTime com_cstdate { get; set; }
        public string com_panno { get; set; }
        public string com_servicetaxno { get; set; }
        public bool com_isdefault { get; set; }
        public string com_logo { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<user> users { get; set; }
        public virtual ICollection<UserType> UserTypes { get; set; }
    }
}
