//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BusinessType> BusinessTypes { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<farm> farms { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<MemberType> MemberTypes { get; set; }
        public DbSet<module> modules { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
    
        public virtual int usp_BusinessTypeDelete(Nullable<long> bt_id)
        {
            var bt_idParameter = bt_id.HasValue ?
                new ObjectParameter("bt_id", bt_id) :
                new ObjectParameter("bt_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_BusinessTypeDelete", bt_idParameter);
        }
    
        public virtual ObjectResult<usp_BusinessTypeInsert_Result> usp_BusinessTypeInsert(string bt_name, Nullable<System.DateTime> bt_cdate, Nullable<System.DateTime> bt_mdate, Nullable<long> bt_cid, Nullable<long> bt_mid)
        {
            var bt_nameParameter = bt_name != null ?
                new ObjectParameter("bt_name", bt_name) :
                new ObjectParameter("bt_name", typeof(string));
    
            var bt_cdateParameter = bt_cdate.HasValue ?
                new ObjectParameter("bt_cdate", bt_cdate) :
                new ObjectParameter("bt_cdate", typeof(System.DateTime));
    
            var bt_mdateParameter = bt_mdate.HasValue ?
                new ObjectParameter("bt_mdate", bt_mdate) :
                new ObjectParameter("bt_mdate", typeof(System.DateTime));
    
            var bt_cidParameter = bt_cid.HasValue ?
                new ObjectParameter("bt_cid", bt_cid) :
                new ObjectParameter("bt_cid", typeof(long));
    
            var bt_midParameter = bt_mid.HasValue ?
                new ObjectParameter("bt_mid", bt_mid) :
                new ObjectParameter("bt_mid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BusinessTypeInsert_Result>("usp_BusinessTypeInsert", bt_nameParameter, bt_cdateParameter, bt_mdateParameter, bt_cidParameter, bt_midParameter);
        }
    
        public virtual ObjectResult<usp_BusinessTypeSelect_Result> usp_BusinessTypeSelect(Nullable<long> bt_id)
        {
            var bt_idParameter = bt_id.HasValue ?
                new ObjectParameter("bt_id", bt_id) :
                new ObjectParameter("bt_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BusinessTypeSelect_Result>("usp_BusinessTypeSelect", bt_idParameter);
        }
    
        public virtual ObjectResult<usp_BusinessTypeUpdate_Result> usp_BusinessTypeUpdate(Nullable<long> bt_id, string bt_name, Nullable<System.DateTime> bt_cdate, Nullable<System.DateTime> bt_mdate, Nullable<long> bt_cid, Nullable<long> bt_mid)
        {
            var bt_idParameter = bt_id.HasValue ?
                new ObjectParameter("bt_id", bt_id) :
                new ObjectParameter("bt_id", typeof(long));
    
            var bt_nameParameter = bt_name != null ?
                new ObjectParameter("bt_name", bt_name) :
                new ObjectParameter("bt_name", typeof(string));
    
            var bt_cdateParameter = bt_cdate.HasValue ?
                new ObjectParameter("bt_cdate", bt_cdate) :
                new ObjectParameter("bt_cdate", typeof(System.DateTime));
    
            var bt_mdateParameter = bt_mdate.HasValue ?
                new ObjectParameter("bt_mdate", bt_mdate) :
                new ObjectParameter("bt_mdate", typeof(System.DateTime));
    
            var bt_cidParameter = bt_cid.HasValue ?
                new ObjectParameter("bt_cid", bt_cid) :
                new ObjectParameter("bt_cid", typeof(long));
    
            var bt_midParameter = bt_mid.HasValue ?
                new ObjectParameter("bt_mid", bt_mid) :
                new ObjectParameter("bt_mid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_BusinessTypeUpdate_Result>("usp_BusinessTypeUpdate", bt_idParameter, bt_nameParameter, bt_cdateParameter, bt_mdateParameter, bt_cidParameter, bt_midParameter);
        }
    
        public virtual int usp_CityDelete(Nullable<long> city_id)
        {
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CityDelete", city_idParameter);
        }
    
        public virtual ObjectResult<usp_CityInsert_Result> usp_CityInsert(string city_name, Nullable<long> con_id, Nullable<long> sta_id)
        {
            var city_nameParameter = city_name != null ?
                new ObjectParameter("city_name", city_name) :
                new ObjectParameter("city_name", typeof(string));
    
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            var sta_idParameter = sta_id.HasValue ?
                new ObjectParameter("sta_id", sta_id) :
                new ObjectParameter("sta_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CityInsert_Result>("usp_CityInsert", city_nameParameter, con_idParameter, sta_idParameter);
        }
    
        public virtual ObjectResult<usp_CitySelect_Result> usp_CitySelect(Nullable<long> city_id, Nullable<long> sta_id, Nullable<long> con_id)
        {
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(long));
    
            var sta_idParameter = sta_id.HasValue ?
                new ObjectParameter("sta_id", sta_id) :
                new ObjectParameter("sta_id", typeof(long));
    
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CitySelect_Result>("usp_CitySelect", city_idParameter, sta_idParameter, con_idParameter);
        }
    
        public virtual ObjectResult<usp_CityUpdate_Result> usp_CityUpdate(Nullable<long> city_id, string city_name, Nullable<long> con_id, Nullable<long> sta_id)
        {
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(long));
    
            var city_nameParameter = city_name != null ?
                new ObjectParameter("city_name", city_name) :
                new ObjectParameter("city_name", typeof(string));
    
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            var sta_idParameter = sta_id.HasValue ?
                new ObjectParameter("sta_id", sta_id) :
                new ObjectParameter("sta_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CityUpdate_Result>("usp_CityUpdate", city_idParameter, city_nameParameter, con_idParameter, sta_idParameter);
        }
    
        public virtual int usp_CompanyDelete(Nullable<long> com_id)
        {
            var com_idParameter = com_id.HasValue ?
                new ObjectParameter("com_id", com_id) :
                new ObjectParameter("com_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CompanyDelete", com_idParameter);
        }
    
        public virtual ObjectResult<usp_CompanyInsert_Result> usp_CompanyInsert(string com_name, string com_invoicename, string com_address1, string com_address2, string com_address3, string com_district, Nullable<long> city_id, Nullable<long> sta_id, Nullable<long> con_id, string com_pincode, string com_mobileno, string com_website, string com_phone, string com_email, string com_tin, string com_cst, Nullable<System.DateTime> com_cstdate, string com_panno, string com_servicetaxno, Nullable<bool> com_isdefault, string com_logo)
        {
            var com_nameParameter = com_name != null ?
                new ObjectParameter("com_name", com_name) :
                new ObjectParameter("com_name", typeof(string));
    
            var com_invoicenameParameter = com_invoicename != null ?
                new ObjectParameter("com_invoicename", com_invoicename) :
                new ObjectParameter("com_invoicename", typeof(string));
    
            var com_address1Parameter = com_address1 != null ?
                new ObjectParameter("com_address1", com_address1) :
                new ObjectParameter("com_address1", typeof(string));
    
            var com_address2Parameter = com_address2 != null ?
                new ObjectParameter("com_address2", com_address2) :
                new ObjectParameter("com_address2", typeof(string));
    
            var com_address3Parameter = com_address3 != null ?
                new ObjectParameter("com_address3", com_address3) :
                new ObjectParameter("com_address3", typeof(string));
    
            var com_districtParameter = com_district != null ?
                new ObjectParameter("com_district", com_district) :
                new ObjectParameter("com_district", typeof(string));
    
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(long));
    
            var sta_idParameter = sta_id.HasValue ?
                new ObjectParameter("sta_id", sta_id) :
                new ObjectParameter("sta_id", typeof(long));
    
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            var com_pincodeParameter = com_pincode != null ?
                new ObjectParameter("com_pincode", com_pincode) :
                new ObjectParameter("com_pincode", typeof(string));
    
            var com_mobilenoParameter = com_mobileno != null ?
                new ObjectParameter("com_mobileno", com_mobileno) :
                new ObjectParameter("com_mobileno", typeof(string));
    
            var com_websiteParameter = com_website != null ?
                new ObjectParameter("com_website", com_website) :
                new ObjectParameter("com_website", typeof(string));
    
            var com_phoneParameter = com_phone != null ?
                new ObjectParameter("com_phone", com_phone) :
                new ObjectParameter("com_phone", typeof(string));
    
            var com_emailParameter = com_email != null ?
                new ObjectParameter("com_email", com_email) :
                new ObjectParameter("com_email", typeof(string));
    
            var com_tinParameter = com_tin != null ?
                new ObjectParameter("com_tin", com_tin) :
                new ObjectParameter("com_tin", typeof(string));
    
            var com_cstParameter = com_cst != null ?
                new ObjectParameter("com_cst", com_cst) :
                new ObjectParameter("com_cst", typeof(string));
    
            var com_cstdateParameter = com_cstdate.HasValue ?
                new ObjectParameter("com_cstdate", com_cstdate) :
                new ObjectParameter("com_cstdate", typeof(System.DateTime));
    
            var com_pannoParameter = com_panno != null ?
                new ObjectParameter("com_panno", com_panno) :
                new ObjectParameter("com_panno", typeof(string));
    
            var com_servicetaxnoParameter = com_servicetaxno != null ?
                new ObjectParameter("com_servicetaxno", com_servicetaxno) :
                new ObjectParameter("com_servicetaxno", typeof(string));
    
            var com_isdefaultParameter = com_isdefault.HasValue ?
                new ObjectParameter("com_isdefault", com_isdefault) :
                new ObjectParameter("com_isdefault", typeof(bool));
    
            var com_logoParameter = com_logo != null ?
                new ObjectParameter("com_logo", com_logo) :
                new ObjectParameter("com_logo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CompanyInsert_Result>("usp_CompanyInsert", com_nameParameter, com_invoicenameParameter, com_address1Parameter, com_address2Parameter, com_address3Parameter, com_districtParameter, city_idParameter, sta_idParameter, con_idParameter, com_pincodeParameter, com_mobilenoParameter, com_websiteParameter, com_phoneParameter, com_emailParameter, com_tinParameter, com_cstParameter, com_cstdateParameter, com_pannoParameter, com_servicetaxnoParameter, com_isdefaultParameter, com_logoParameter);
        }
    
        public virtual ObjectResult<usp_CompanySelect_Result> usp_CompanySelect(Nullable<long> com_id)
        {
            var com_idParameter = com_id.HasValue ?
                new ObjectParameter("com_id", com_id) :
                new ObjectParameter("com_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CompanySelect_Result>("usp_CompanySelect", com_idParameter);
        }
    
        public virtual ObjectResult<usp_CompanyUpdate_Result> usp_CompanyUpdate(Nullable<long> com_id, string com_name, string com_invoicename, string com_address1, string com_address2, string com_address3, string com_district, Nullable<long> city_id, Nullable<long> sta_id, Nullable<long> con_id, string com_pincode, string com_mobileno, string com_website, string com_phone, string com_email, string com_tin, string com_cst, Nullable<System.DateTime> com_cstdate, string com_panno, string com_servicetaxno, Nullable<bool> com_isdefault, string com_logo)
        {
            var com_idParameter = com_id.HasValue ?
                new ObjectParameter("com_id", com_id) :
                new ObjectParameter("com_id", typeof(long));
    
            var com_nameParameter = com_name != null ?
                new ObjectParameter("com_name", com_name) :
                new ObjectParameter("com_name", typeof(string));
    
            var com_invoicenameParameter = com_invoicename != null ?
                new ObjectParameter("com_invoicename", com_invoicename) :
                new ObjectParameter("com_invoicename", typeof(string));
    
            var com_address1Parameter = com_address1 != null ?
                new ObjectParameter("com_address1", com_address1) :
                new ObjectParameter("com_address1", typeof(string));
    
            var com_address2Parameter = com_address2 != null ?
                new ObjectParameter("com_address2", com_address2) :
                new ObjectParameter("com_address2", typeof(string));
    
            var com_address3Parameter = com_address3 != null ?
                new ObjectParameter("com_address3", com_address3) :
                new ObjectParameter("com_address3", typeof(string));
    
            var com_districtParameter = com_district != null ?
                new ObjectParameter("com_district", com_district) :
                new ObjectParameter("com_district", typeof(string));
    
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(long));
    
            var sta_idParameter = sta_id.HasValue ?
                new ObjectParameter("sta_id", sta_id) :
                new ObjectParameter("sta_id", typeof(long));
    
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            var com_pincodeParameter = com_pincode != null ?
                new ObjectParameter("com_pincode", com_pincode) :
                new ObjectParameter("com_pincode", typeof(string));
    
            var com_mobilenoParameter = com_mobileno != null ?
                new ObjectParameter("com_mobileno", com_mobileno) :
                new ObjectParameter("com_mobileno", typeof(string));
    
            var com_websiteParameter = com_website != null ?
                new ObjectParameter("com_website", com_website) :
                new ObjectParameter("com_website", typeof(string));
    
            var com_phoneParameter = com_phone != null ?
                new ObjectParameter("com_phone", com_phone) :
                new ObjectParameter("com_phone", typeof(string));
    
            var com_emailParameter = com_email != null ?
                new ObjectParameter("com_email", com_email) :
                new ObjectParameter("com_email", typeof(string));
    
            var com_tinParameter = com_tin != null ?
                new ObjectParameter("com_tin", com_tin) :
                new ObjectParameter("com_tin", typeof(string));
    
            var com_cstParameter = com_cst != null ?
                new ObjectParameter("com_cst", com_cst) :
                new ObjectParameter("com_cst", typeof(string));
    
            var com_cstdateParameter = com_cstdate.HasValue ?
                new ObjectParameter("com_cstdate", com_cstdate) :
                new ObjectParameter("com_cstdate", typeof(System.DateTime));
    
            var com_pannoParameter = com_panno != null ?
                new ObjectParameter("com_panno", com_panno) :
                new ObjectParameter("com_panno", typeof(string));
    
            var com_servicetaxnoParameter = com_servicetaxno != null ?
                new ObjectParameter("com_servicetaxno", com_servicetaxno) :
                new ObjectParameter("com_servicetaxno", typeof(string));
    
            var com_isdefaultParameter = com_isdefault.HasValue ?
                new ObjectParameter("com_isdefault", com_isdefault) :
                new ObjectParameter("com_isdefault", typeof(bool));
    
            var com_logoParameter = com_logo != null ?
                new ObjectParameter("com_logo", com_logo) :
                new ObjectParameter("com_logo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CompanyUpdate_Result>("usp_CompanyUpdate", com_idParameter, com_nameParameter, com_invoicenameParameter, com_address1Parameter, com_address2Parameter, com_address3Parameter, com_districtParameter, city_idParameter, sta_idParameter, con_idParameter, com_pincodeParameter, com_mobilenoParameter, com_websiteParameter, com_phoneParameter, com_emailParameter, com_tinParameter, com_cstParameter, com_cstdateParameter, com_pannoParameter, com_servicetaxnoParameter, com_isdefaultParameter, com_logoParameter);
        }
    
        public virtual int usp_CountryDelete(Nullable<long> con_id)
        {
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CountryDelete", con_idParameter);
        }
    
        public virtual ObjectResult<usp_CountryInsert_Result> usp_CountryInsert(string con_name)
        {
            var con_nameParameter = con_name != null ?
                new ObjectParameter("con_name", con_name) :
                new ObjectParameter("con_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CountryInsert_Result>("usp_CountryInsert", con_nameParameter);
        }
    
        public virtual ObjectResult<usp_CountrySelect_Result> usp_CountrySelect(Nullable<long> con_id)
        {
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CountrySelect_Result>("usp_CountrySelect", con_idParameter);
        }
    
        public virtual ObjectResult<usp_CountryUpdate_Result> usp_CountryUpdate(Nullable<long> con_id, string con_name)
        {
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            var con_nameParameter = con_name != null ?
                new ObjectParameter("con_name", con_name) :
                new ObjectParameter("con_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CountryUpdate_Result>("usp_CountryUpdate", con_idParameter, con_nameParameter);
        }
    
        public virtual int usp_CustomerDelete(Nullable<long> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CustomerDelete", cust_idParameter);
        }
    
        public virtual ObjectResult<usp_CustomerInsert_Result> usp_CustomerInsert(Nullable<long> cust_code, string cust_type, string cust_name, string cust_brand, string cust_contactperson, string cust_address1, string cust_address2, string cust_address3, string cust_city, string cust_district, string cust_state, string cust_pincode, string cust_mobile, string cust_phone, string cust_mobile2, string cust_email, string cust_webbsite, string cust_gstno)
        {
            var cust_codeParameter = cust_code.HasValue ?
                new ObjectParameter("cust_code", cust_code) :
                new ObjectParameter("cust_code", typeof(long));
    
            var cust_typeParameter = cust_type != null ?
                new ObjectParameter("cust_type", cust_type) :
                new ObjectParameter("cust_type", typeof(string));
    
            var cust_nameParameter = cust_name != null ?
                new ObjectParameter("cust_name", cust_name) :
                new ObjectParameter("cust_name", typeof(string));
    
            var cust_brandParameter = cust_brand != null ?
                new ObjectParameter("cust_brand", cust_brand) :
                new ObjectParameter("cust_brand", typeof(string));
    
            var cust_contactpersonParameter = cust_contactperson != null ?
                new ObjectParameter("cust_contactperson", cust_contactperson) :
                new ObjectParameter("cust_contactperson", typeof(string));
    
            var cust_address1Parameter = cust_address1 != null ?
                new ObjectParameter("cust_address1", cust_address1) :
                new ObjectParameter("cust_address1", typeof(string));
    
            var cust_address2Parameter = cust_address2 != null ?
                new ObjectParameter("cust_address2", cust_address2) :
                new ObjectParameter("cust_address2", typeof(string));
    
            var cust_address3Parameter = cust_address3 != null ?
                new ObjectParameter("cust_address3", cust_address3) :
                new ObjectParameter("cust_address3", typeof(string));
    
            var cust_cityParameter = cust_city != null ?
                new ObjectParameter("cust_city", cust_city) :
                new ObjectParameter("cust_city", typeof(string));
    
            var cust_districtParameter = cust_district != null ?
                new ObjectParameter("cust_district", cust_district) :
                new ObjectParameter("cust_district", typeof(string));
    
            var cust_stateParameter = cust_state != null ?
                new ObjectParameter("cust_state", cust_state) :
                new ObjectParameter("cust_state", typeof(string));
    
            var cust_pincodeParameter = cust_pincode != null ?
                new ObjectParameter("cust_pincode", cust_pincode) :
                new ObjectParameter("cust_pincode", typeof(string));
    
            var cust_mobileParameter = cust_mobile != null ?
                new ObjectParameter("cust_mobile", cust_mobile) :
                new ObjectParameter("cust_mobile", typeof(string));
    
            var cust_phoneParameter = cust_phone != null ?
                new ObjectParameter("cust_phone", cust_phone) :
                new ObjectParameter("cust_phone", typeof(string));
    
            var cust_mobile2Parameter = cust_mobile2 != null ?
                new ObjectParameter("cust_mobile2", cust_mobile2) :
                new ObjectParameter("cust_mobile2", typeof(string));
    
            var cust_emailParameter = cust_email != null ?
                new ObjectParameter("cust_email", cust_email) :
                new ObjectParameter("cust_email", typeof(string));
    
            var cust_webbsiteParameter = cust_webbsite != null ?
                new ObjectParameter("cust_webbsite", cust_webbsite) :
                new ObjectParameter("cust_webbsite", typeof(string));
    
            var cust_gstnoParameter = cust_gstno != null ?
                new ObjectParameter("cust_gstno", cust_gstno) :
                new ObjectParameter("cust_gstno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CustomerInsert_Result>("usp_CustomerInsert", cust_codeParameter, cust_typeParameter, cust_nameParameter, cust_brandParameter, cust_contactpersonParameter, cust_address1Parameter, cust_address2Parameter, cust_address3Parameter, cust_cityParameter, cust_districtParameter, cust_stateParameter, cust_pincodeParameter, cust_mobileParameter, cust_phoneParameter, cust_mobile2Parameter, cust_emailParameter, cust_webbsiteParameter, cust_gstnoParameter);
        }
    
        public virtual ObjectResult<usp_CustomerSelect_Result> usp_CustomerSelect(Nullable<long> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CustomerSelect_Result>("usp_CustomerSelect", cust_idParameter);
        }
    
        public virtual ObjectResult<usp_CustomerUpdate_Result> usp_CustomerUpdate(Nullable<long> cust_id, Nullable<long> cust_code, string cust_type, string cust_name, string cust_brand, string cust_contactperson, string cust_address1, string cust_address2, string cust_address3, string cust_city, string cust_district, string cust_state, string cust_pincode, string cust_mobile, string cust_phone, string cust_mobile2, string cust_email, string cust_webbsite, string cust_gstno)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(long));
    
            var cust_codeParameter = cust_code.HasValue ?
                new ObjectParameter("cust_code", cust_code) :
                new ObjectParameter("cust_code", typeof(long));
    
            var cust_typeParameter = cust_type != null ?
                new ObjectParameter("cust_type", cust_type) :
                new ObjectParameter("cust_type", typeof(string));
    
            var cust_nameParameter = cust_name != null ?
                new ObjectParameter("cust_name", cust_name) :
                new ObjectParameter("cust_name", typeof(string));
    
            var cust_brandParameter = cust_brand != null ?
                new ObjectParameter("cust_brand", cust_brand) :
                new ObjectParameter("cust_brand", typeof(string));
    
            var cust_contactpersonParameter = cust_contactperson != null ?
                new ObjectParameter("cust_contactperson", cust_contactperson) :
                new ObjectParameter("cust_contactperson", typeof(string));
    
            var cust_address1Parameter = cust_address1 != null ?
                new ObjectParameter("cust_address1", cust_address1) :
                new ObjectParameter("cust_address1", typeof(string));
    
            var cust_address2Parameter = cust_address2 != null ?
                new ObjectParameter("cust_address2", cust_address2) :
                new ObjectParameter("cust_address2", typeof(string));
    
            var cust_address3Parameter = cust_address3 != null ?
                new ObjectParameter("cust_address3", cust_address3) :
                new ObjectParameter("cust_address3", typeof(string));
    
            var cust_cityParameter = cust_city != null ?
                new ObjectParameter("cust_city", cust_city) :
                new ObjectParameter("cust_city", typeof(string));
    
            var cust_districtParameter = cust_district != null ?
                new ObjectParameter("cust_district", cust_district) :
                new ObjectParameter("cust_district", typeof(string));
    
            var cust_stateParameter = cust_state != null ?
                new ObjectParameter("cust_state", cust_state) :
                new ObjectParameter("cust_state", typeof(string));
    
            var cust_pincodeParameter = cust_pincode != null ?
                new ObjectParameter("cust_pincode", cust_pincode) :
                new ObjectParameter("cust_pincode", typeof(string));
    
            var cust_mobileParameter = cust_mobile != null ?
                new ObjectParameter("cust_mobile", cust_mobile) :
                new ObjectParameter("cust_mobile", typeof(string));
    
            var cust_phoneParameter = cust_phone != null ?
                new ObjectParameter("cust_phone", cust_phone) :
                new ObjectParameter("cust_phone", typeof(string));
    
            var cust_mobile2Parameter = cust_mobile2 != null ?
                new ObjectParameter("cust_mobile2", cust_mobile2) :
                new ObjectParameter("cust_mobile2", typeof(string));
    
            var cust_emailParameter = cust_email != null ?
                new ObjectParameter("cust_email", cust_email) :
                new ObjectParameter("cust_email", typeof(string));
    
            var cust_webbsiteParameter = cust_webbsite != null ?
                new ObjectParameter("cust_webbsite", cust_webbsite) :
                new ObjectParameter("cust_webbsite", typeof(string));
    
            var cust_gstnoParameter = cust_gstno != null ?
                new ObjectParameter("cust_gstno", cust_gstno) :
                new ObjectParameter("cust_gstno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_CustomerUpdate_Result>("usp_CustomerUpdate", cust_idParameter, cust_codeParameter, cust_typeParameter, cust_nameParameter, cust_brandParameter, cust_contactpersonParameter, cust_address1Parameter, cust_address2Parameter, cust_address3Parameter, cust_cityParameter, cust_districtParameter, cust_stateParameter, cust_pincodeParameter, cust_mobileParameter, cust_phoneParameter, cust_mobile2Parameter, cust_emailParameter, cust_webbsiteParameter, cust_gstnoParameter);
        }
    
        public virtual int usp_farmDelete(Nullable<long> farm_id)
        {
            var farm_idParameter = farm_id.HasValue ?
                new ObjectParameter("farm_id", farm_id) :
                new ObjectParameter("farm_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_farmDelete", farm_idParameter);
        }
    
        public virtual ObjectResult<usp_farmInsert_Result> usp_farmInsert(Nullable<long> farm_id, Nullable<long> module_id, string farm_name, string farm_add, string farm_edit, string farm_delete, string farm_view, string farm_print)
        {
            var farm_idParameter = farm_id.HasValue ?
                new ObjectParameter("farm_id", farm_id) :
                new ObjectParameter("farm_id", typeof(long));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(long));
    
            var farm_nameParameter = farm_name != null ?
                new ObjectParameter("farm_name", farm_name) :
                new ObjectParameter("farm_name", typeof(string));
    
            var farm_addParameter = farm_add != null ?
                new ObjectParameter("farm_add", farm_add) :
                new ObjectParameter("farm_add", typeof(string));
    
            var farm_editParameter = farm_edit != null ?
                new ObjectParameter("farm_edit", farm_edit) :
                new ObjectParameter("farm_edit", typeof(string));
    
            var farm_deleteParameter = farm_delete != null ?
                new ObjectParameter("farm_delete", farm_delete) :
                new ObjectParameter("farm_delete", typeof(string));
    
            var farm_viewParameter = farm_view != null ?
                new ObjectParameter("farm_view", farm_view) :
                new ObjectParameter("farm_view", typeof(string));
    
            var farm_printParameter = farm_print != null ?
                new ObjectParameter("farm_print", farm_print) :
                new ObjectParameter("farm_print", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_farmInsert_Result>("usp_farmInsert", farm_idParameter, module_idParameter, farm_nameParameter, farm_addParameter, farm_editParameter, farm_deleteParameter, farm_viewParameter, farm_printParameter);
        }
    
        public virtual ObjectResult<usp_farmSelect_Result> usp_farmSelect(Nullable<long> farm_id)
        {
            var farm_idParameter = farm_id.HasValue ?
                new ObjectParameter("farm_id", farm_id) :
                new ObjectParameter("farm_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_farmSelect_Result>("usp_farmSelect", farm_idParameter);
        }
    
        public virtual ObjectResult<usp_farmUpdate_Result> usp_farmUpdate(Nullable<long> farm_id, Nullable<long> module_id, string farm_name, string farm_add, string farm_edit, string farm_delete, string farm_view, string farm_print)
        {
            var farm_idParameter = farm_id.HasValue ?
                new ObjectParameter("farm_id", farm_id) :
                new ObjectParameter("farm_id", typeof(long));
    
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(long));
    
            var farm_nameParameter = farm_name != null ?
                new ObjectParameter("farm_name", farm_name) :
                new ObjectParameter("farm_name", typeof(string));
    
            var farm_addParameter = farm_add != null ?
                new ObjectParameter("farm_add", farm_add) :
                new ObjectParameter("farm_add", typeof(string));
    
            var farm_editParameter = farm_edit != null ?
                new ObjectParameter("farm_edit", farm_edit) :
                new ObjectParameter("farm_edit", typeof(string));
    
            var farm_deleteParameter = farm_delete != null ?
                new ObjectParameter("farm_delete", farm_delete) :
                new ObjectParameter("farm_delete", typeof(string));
    
            var farm_viewParameter = farm_view != null ?
                new ObjectParameter("farm_view", farm_view) :
                new ObjectParameter("farm_view", typeof(string));
    
            var farm_printParameter = farm_print != null ?
                new ObjectParameter("farm_print", farm_print) :
                new ObjectParameter("farm_print", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_farmUpdate_Result>("usp_farmUpdate", farm_idParameter, module_idParameter, farm_nameParameter, farm_addParameter, farm_editParameter, farm_deleteParameter, farm_viewParameter, farm_printParameter);
        }
    
        public virtual int usp_MemberDelete(Nullable<long> mem_id)
        {
            var mem_idParameter = mem_id.HasValue ?
                new ObjectParameter("mem_id", mem_id) :
                new ObjectParameter("mem_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MemberDelete", mem_idParameter);
        }
    
        public virtual ObjectResult<usp_MemberInsert_Result> usp_MemberInsert(Nullable<long> mt_id, Nullable<long> bt_id, string mem_name, string mem_companyname, string mem_owner, string mem_address1, string mem_address2, string mem_offaddress1, string mem_offaddress2, Nullable<long> city_id, Nullable<long> sta_id, Nullable<long> con_id, string mem_pincode, string mem_mobile, string mem_phone, string mem_offphone, string mem_email, string mem_webbsite, string mem_gstno, string mem_panno, string mem_logo, Nullable<System.DateTime> mem_cdate, Nullable<System.DateTime> mem_mdate, Nullable<long> mem_cid, Nullable<long> mem_mid)
        {
            var mt_idParameter = mt_id.HasValue ?
                new ObjectParameter("mt_id", mt_id) :
                new ObjectParameter("mt_id", typeof(long));
    
            var bt_idParameter = bt_id.HasValue ?
                new ObjectParameter("bt_id", bt_id) :
                new ObjectParameter("bt_id", typeof(long));
    
            var mem_nameParameter = mem_name != null ?
                new ObjectParameter("mem_name", mem_name) :
                new ObjectParameter("mem_name", typeof(string));
    
            var mem_companynameParameter = mem_companyname != null ?
                new ObjectParameter("mem_companyname", mem_companyname) :
                new ObjectParameter("mem_companyname", typeof(string));
    
            var mem_ownerParameter = mem_owner != null ?
                new ObjectParameter("mem_owner", mem_owner) :
                new ObjectParameter("mem_owner", typeof(string));
    
            var mem_address1Parameter = mem_address1 != null ?
                new ObjectParameter("mem_address1", mem_address1) :
                new ObjectParameter("mem_address1", typeof(string));
    
            var mem_address2Parameter = mem_address2 != null ?
                new ObjectParameter("mem_address2", mem_address2) :
                new ObjectParameter("mem_address2", typeof(string));
    
            var mem_offaddress1Parameter = mem_offaddress1 != null ?
                new ObjectParameter("mem_offaddress1", mem_offaddress1) :
                new ObjectParameter("mem_offaddress1", typeof(string));
    
            var mem_offaddress2Parameter = mem_offaddress2 != null ?
                new ObjectParameter("mem_offaddress2", mem_offaddress2) :
                new ObjectParameter("mem_offaddress2", typeof(string));
    
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(long));
    
            var sta_idParameter = sta_id.HasValue ?
                new ObjectParameter("sta_id", sta_id) :
                new ObjectParameter("sta_id", typeof(long));
    
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            var mem_pincodeParameter = mem_pincode != null ?
                new ObjectParameter("mem_pincode", mem_pincode) :
                new ObjectParameter("mem_pincode", typeof(string));
    
            var mem_mobileParameter = mem_mobile != null ?
                new ObjectParameter("mem_mobile", mem_mobile) :
                new ObjectParameter("mem_mobile", typeof(string));
    
            var mem_phoneParameter = mem_phone != null ?
                new ObjectParameter("mem_phone", mem_phone) :
                new ObjectParameter("mem_phone", typeof(string));
    
            var mem_offphoneParameter = mem_offphone != null ?
                new ObjectParameter("mem_offphone", mem_offphone) :
                new ObjectParameter("mem_offphone", typeof(string));
    
            var mem_emailParameter = mem_email != null ?
                new ObjectParameter("mem_email", mem_email) :
                new ObjectParameter("mem_email", typeof(string));
    
            var mem_webbsiteParameter = mem_webbsite != null ?
                new ObjectParameter("mem_webbsite", mem_webbsite) :
                new ObjectParameter("mem_webbsite", typeof(string));
    
            var mem_gstnoParameter = mem_gstno != null ?
                new ObjectParameter("mem_gstno", mem_gstno) :
                new ObjectParameter("mem_gstno", typeof(string));
    
            var mem_pannoParameter = mem_panno != null ?
                new ObjectParameter("mem_panno", mem_panno) :
                new ObjectParameter("mem_panno", typeof(string));
    
            var mem_logoParameter = mem_logo != null ?
                new ObjectParameter("mem_logo", mem_logo) :
                new ObjectParameter("mem_logo", typeof(string));
    
            var mem_cdateParameter = mem_cdate.HasValue ?
                new ObjectParameter("mem_cdate", mem_cdate) :
                new ObjectParameter("mem_cdate", typeof(System.DateTime));
    
            var mem_mdateParameter = mem_mdate.HasValue ?
                new ObjectParameter("mem_mdate", mem_mdate) :
                new ObjectParameter("mem_mdate", typeof(System.DateTime));
    
            var mem_cidParameter = mem_cid.HasValue ?
                new ObjectParameter("mem_cid", mem_cid) :
                new ObjectParameter("mem_cid", typeof(long));
    
            var mem_midParameter = mem_mid.HasValue ?
                new ObjectParameter("mem_mid", mem_mid) :
                new ObjectParameter("mem_mid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MemberInsert_Result>("usp_MemberInsert", mt_idParameter, bt_idParameter, mem_nameParameter, mem_companynameParameter, mem_ownerParameter, mem_address1Parameter, mem_address2Parameter, mem_offaddress1Parameter, mem_offaddress2Parameter, city_idParameter, sta_idParameter, con_idParameter, mem_pincodeParameter, mem_mobileParameter, mem_phoneParameter, mem_offphoneParameter, mem_emailParameter, mem_webbsiteParameter, mem_gstnoParameter, mem_pannoParameter, mem_logoParameter, mem_cdateParameter, mem_mdateParameter, mem_cidParameter, mem_midParameter);
        }
    
        public virtual ObjectResult<usp_MemberSelect_Result> usp_MemberSelect(Nullable<long> mem_id)
        {
            var mem_idParameter = mem_id.HasValue ?
                new ObjectParameter("mem_id", mem_id) :
                new ObjectParameter("mem_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MemberSelect_Result>("usp_MemberSelect", mem_idParameter);
        }
    
        public virtual int usp_MemberTypeDelete(Nullable<long> mt_id)
        {
            var mt_idParameter = mt_id.HasValue ?
                new ObjectParameter("mt_id", mt_id) :
                new ObjectParameter("mt_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_MemberTypeDelete", mt_idParameter);
        }
    
        public virtual ObjectResult<usp_MemberTypeInsert_Result> usp_MemberTypeInsert(string mt_name, Nullable<System.DateTime> mt_cdate, Nullable<System.DateTime> mt_mdate, Nullable<long> mt_cid, Nullable<long> mt_mid)
        {
            var mt_nameParameter = mt_name != null ?
                new ObjectParameter("mt_name", mt_name) :
                new ObjectParameter("mt_name", typeof(string));
    
            var mt_cdateParameter = mt_cdate.HasValue ?
                new ObjectParameter("mt_cdate", mt_cdate) :
                new ObjectParameter("mt_cdate", typeof(System.DateTime));
    
            var mt_mdateParameter = mt_mdate.HasValue ?
                new ObjectParameter("mt_mdate", mt_mdate) :
                new ObjectParameter("mt_mdate", typeof(System.DateTime));
    
            var mt_cidParameter = mt_cid.HasValue ?
                new ObjectParameter("mt_cid", mt_cid) :
                new ObjectParameter("mt_cid", typeof(long));
    
            var mt_midParameter = mt_mid.HasValue ?
                new ObjectParameter("mt_mid", mt_mid) :
                new ObjectParameter("mt_mid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MemberTypeInsert_Result>("usp_MemberTypeInsert", mt_nameParameter, mt_cdateParameter, mt_mdateParameter, mt_cidParameter, mt_midParameter);
        }
    
        public virtual ObjectResult<usp_MemberTypeSelect_Result> usp_MemberTypeSelect(Nullable<long> mt_id)
        {
            var mt_idParameter = mt_id.HasValue ?
                new ObjectParameter("mt_id", mt_id) :
                new ObjectParameter("mt_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MemberTypeSelect_Result>("usp_MemberTypeSelect", mt_idParameter);
        }
    
        public virtual ObjectResult<usp_MemberTypeUpdate_Result> usp_MemberTypeUpdate(Nullable<long> mt_id, string mt_name, Nullable<System.DateTime> mt_cdate, Nullable<System.DateTime> mt_mdate, Nullable<long> mt_cid, Nullable<long> mt_mid)
        {
            var mt_idParameter = mt_id.HasValue ?
                new ObjectParameter("mt_id", mt_id) :
                new ObjectParameter("mt_id", typeof(long));
    
            var mt_nameParameter = mt_name != null ?
                new ObjectParameter("mt_name", mt_name) :
                new ObjectParameter("mt_name", typeof(string));
    
            var mt_cdateParameter = mt_cdate.HasValue ?
                new ObjectParameter("mt_cdate", mt_cdate) :
                new ObjectParameter("mt_cdate", typeof(System.DateTime));
    
            var mt_mdateParameter = mt_mdate.HasValue ?
                new ObjectParameter("mt_mdate", mt_mdate) :
                new ObjectParameter("mt_mdate", typeof(System.DateTime));
    
            var mt_cidParameter = mt_cid.HasValue ?
                new ObjectParameter("mt_cid", mt_cid) :
                new ObjectParameter("mt_cid", typeof(long));
    
            var mt_midParameter = mt_mid.HasValue ?
                new ObjectParameter("mt_mid", mt_mid) :
                new ObjectParameter("mt_mid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MemberTypeUpdate_Result>("usp_MemberTypeUpdate", mt_idParameter, mt_nameParameter, mt_cdateParameter, mt_mdateParameter, mt_cidParameter, mt_midParameter);
        }
    
        public virtual ObjectResult<usp_MemberUpdate_Result> usp_MemberUpdate(Nullable<long> mem_id, Nullable<long> mt_id, Nullable<long> bt_id, string mem_name, string mem_companyname, string mem_owner, string mem_address1, string mem_address2, string mem_offaddress1, string mem_offaddress2, Nullable<long> city_id, Nullable<long> sta_id, Nullable<long> con_id, string mem_pincode, string mem_mobile, string mem_phone, string mem_offphone, string mem_email, string mem_webbsite, string mem_gstno, string mem_panno, string mem_logo, Nullable<System.DateTime> mem_cdate, Nullable<System.DateTime> mem_mdate, Nullable<long> mem_cid, Nullable<long> mem_mid)
        {
            var mem_idParameter = mem_id.HasValue ?
                new ObjectParameter("mem_id", mem_id) :
                new ObjectParameter("mem_id", typeof(long));
    
            var mt_idParameter = mt_id.HasValue ?
                new ObjectParameter("mt_id", mt_id) :
                new ObjectParameter("mt_id", typeof(long));
    
            var bt_idParameter = bt_id.HasValue ?
                new ObjectParameter("bt_id", bt_id) :
                new ObjectParameter("bt_id", typeof(long));
    
            var mem_nameParameter = mem_name != null ?
                new ObjectParameter("mem_name", mem_name) :
                new ObjectParameter("mem_name", typeof(string));
    
            var mem_companynameParameter = mem_companyname != null ?
                new ObjectParameter("mem_companyname", mem_companyname) :
                new ObjectParameter("mem_companyname", typeof(string));
    
            var mem_ownerParameter = mem_owner != null ?
                new ObjectParameter("mem_owner", mem_owner) :
                new ObjectParameter("mem_owner", typeof(string));
    
            var mem_address1Parameter = mem_address1 != null ?
                new ObjectParameter("mem_address1", mem_address1) :
                new ObjectParameter("mem_address1", typeof(string));
    
            var mem_address2Parameter = mem_address2 != null ?
                new ObjectParameter("mem_address2", mem_address2) :
                new ObjectParameter("mem_address2", typeof(string));
    
            var mem_offaddress1Parameter = mem_offaddress1 != null ?
                new ObjectParameter("mem_offaddress1", mem_offaddress1) :
                new ObjectParameter("mem_offaddress1", typeof(string));
    
            var mem_offaddress2Parameter = mem_offaddress2 != null ?
                new ObjectParameter("mem_offaddress2", mem_offaddress2) :
                new ObjectParameter("mem_offaddress2", typeof(string));
    
            var city_idParameter = city_id.HasValue ?
                new ObjectParameter("city_id", city_id) :
                new ObjectParameter("city_id", typeof(long));
    
            var sta_idParameter = sta_id.HasValue ?
                new ObjectParameter("sta_id", sta_id) :
                new ObjectParameter("sta_id", typeof(long));
    
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            var mem_pincodeParameter = mem_pincode != null ?
                new ObjectParameter("mem_pincode", mem_pincode) :
                new ObjectParameter("mem_pincode", typeof(string));
    
            var mem_mobileParameter = mem_mobile != null ?
                new ObjectParameter("mem_mobile", mem_mobile) :
                new ObjectParameter("mem_mobile", typeof(string));
    
            var mem_phoneParameter = mem_phone != null ?
                new ObjectParameter("mem_phone", mem_phone) :
                new ObjectParameter("mem_phone", typeof(string));
    
            var mem_offphoneParameter = mem_offphone != null ?
                new ObjectParameter("mem_offphone", mem_offphone) :
                new ObjectParameter("mem_offphone", typeof(string));
    
            var mem_emailParameter = mem_email != null ?
                new ObjectParameter("mem_email", mem_email) :
                new ObjectParameter("mem_email", typeof(string));
    
            var mem_webbsiteParameter = mem_webbsite != null ?
                new ObjectParameter("mem_webbsite", mem_webbsite) :
                new ObjectParameter("mem_webbsite", typeof(string));
    
            var mem_gstnoParameter = mem_gstno != null ?
                new ObjectParameter("mem_gstno", mem_gstno) :
                new ObjectParameter("mem_gstno", typeof(string));
    
            var mem_pannoParameter = mem_panno != null ?
                new ObjectParameter("mem_panno", mem_panno) :
                new ObjectParameter("mem_panno", typeof(string));
    
            var mem_logoParameter = mem_logo != null ?
                new ObjectParameter("mem_logo", mem_logo) :
                new ObjectParameter("mem_logo", typeof(string));
    
            var mem_cdateParameter = mem_cdate.HasValue ?
                new ObjectParameter("mem_cdate", mem_cdate) :
                new ObjectParameter("mem_cdate", typeof(System.DateTime));
    
            var mem_mdateParameter = mem_mdate.HasValue ?
                new ObjectParameter("mem_mdate", mem_mdate) :
                new ObjectParameter("mem_mdate", typeof(System.DateTime));
    
            var mem_cidParameter = mem_cid.HasValue ?
                new ObjectParameter("mem_cid", mem_cid) :
                new ObjectParameter("mem_cid", typeof(long));
    
            var mem_midParameter = mem_mid.HasValue ?
                new ObjectParameter("mem_mid", mem_mid) :
                new ObjectParameter("mem_mid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MemberUpdate_Result>("usp_MemberUpdate", mem_idParameter, mt_idParameter, bt_idParameter, mem_nameParameter, mem_companynameParameter, mem_ownerParameter, mem_address1Parameter, mem_address2Parameter, mem_offaddress1Parameter, mem_offaddress2Parameter, city_idParameter, sta_idParameter, con_idParameter, mem_pincodeParameter, mem_mobileParameter, mem_phoneParameter, mem_offphoneParameter, mem_emailParameter, mem_webbsiteParameter, mem_gstnoParameter, mem_pannoParameter, mem_logoParameter, mem_cdateParameter, mem_mdateParameter, mem_cidParameter, mem_midParameter);
        }
    
        public virtual int usp_moduleDelete(Nullable<long> module_id)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_moduleDelete", module_idParameter);
        }
    
        public virtual ObjectResult<usp_moduleInsert_Result> usp_moduleInsert(Nullable<long> module_id, string module_name)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(long));
    
            var module_nameParameter = module_name != null ?
                new ObjectParameter("module_name", module_name) :
                new ObjectParameter("module_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_moduleInsert_Result>("usp_moduleInsert", module_idParameter, module_nameParameter);
        }
    
        public virtual ObjectResult<usp_moduleSelect_Result> usp_moduleSelect(Nullable<long> module_id)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_moduleSelect_Result>("usp_moduleSelect", module_idParameter);
        }
    
        public virtual ObjectResult<usp_moduleUpdate_Result> usp_moduleUpdate(Nullable<long> module_id, string module_name)
        {
            var module_idParameter = module_id.HasValue ?
                new ObjectParameter("module_id", module_id) :
                new ObjectParameter("module_id", typeof(long));
    
            var module_nameParameter = module_name != null ?
                new ObjectParameter("module_name", module_name) :
                new ObjectParameter("module_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_moduleUpdate_Result>("usp_moduleUpdate", module_idParameter, module_nameParameter);
        }
    
        public virtual int usp_rightsDelete(Nullable<int> users_id)
        {
            var users_idParameter = users_id.HasValue ?
                new ObjectParameter("users_id", users_id) :
                new ObjectParameter("users_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_rightsDelete", users_idParameter);
        }
    
        public virtual int usp_rightsInsert(Nullable<int> farm_id, Nullable<int> users_id, string farm_add, string farm_edit, string farm_delete, string farm_view, string farm_print)
        {
            var farm_idParameter = farm_id.HasValue ?
                new ObjectParameter("farm_id", farm_id) :
                new ObjectParameter("farm_id", typeof(int));
    
            var users_idParameter = users_id.HasValue ?
                new ObjectParameter("users_id", users_id) :
                new ObjectParameter("users_id", typeof(int));
    
            var farm_addParameter = farm_add != null ?
                new ObjectParameter("farm_add", farm_add) :
                new ObjectParameter("farm_add", typeof(string));
    
            var farm_editParameter = farm_edit != null ?
                new ObjectParameter("farm_edit", farm_edit) :
                new ObjectParameter("farm_edit", typeof(string));
    
            var farm_deleteParameter = farm_delete != null ?
                new ObjectParameter("farm_delete", farm_delete) :
                new ObjectParameter("farm_delete", typeof(string));
    
            var farm_viewParameter = farm_view != null ?
                new ObjectParameter("farm_view", farm_view) :
                new ObjectParameter("farm_view", typeof(string));
    
            var farm_printParameter = farm_print != null ?
                new ObjectParameter("farm_print", farm_print) :
                new ObjectParameter("farm_print", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_rightsInsert", farm_idParameter, users_idParameter, farm_addParameter, farm_editParameter, farm_deleteParameter, farm_viewParameter, farm_printParameter);
        }
    
        public virtual ObjectResult<usp_rightsSelect_Result> usp_rightsSelect(Nullable<int> rusers_id, Nullable<int> users_id)
        {
            var rusers_idParameter = rusers_id.HasValue ?
                new ObjectParameter("rusers_id", rusers_id) :
                new ObjectParameter("rusers_id", typeof(int));
    
            var users_idParameter = users_id.HasValue ?
                new ObjectParameter("users_id", users_id) :
                new ObjectParameter("users_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_rightsSelect_Result>("usp_rightsSelect", rusers_idParameter, users_idParameter);
        }
    
        public virtual int usp_StatesDelete(Nullable<long> sta_id)
        {
            var sta_idParameter = sta_id.HasValue ?
                new ObjectParameter("sta_id", sta_id) :
                new ObjectParameter("sta_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_StatesDelete", sta_idParameter);
        }
    
        public virtual ObjectResult<usp_StatesInsert_Result> usp_StatesInsert(string sta_name, Nullable<long> con_id)
        {
            var sta_nameParameter = sta_name != null ?
                new ObjectParameter("sta_name", sta_name) :
                new ObjectParameter("sta_name", typeof(string));
    
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_StatesInsert_Result>("usp_StatesInsert", sta_nameParameter, con_idParameter);
        }
    
        public virtual ObjectResult<usp_StatesSelect_Result> usp_StatesSelect(Nullable<long> sta_id, Nullable<long> con_id)
        {
            var sta_idParameter = sta_id.HasValue ?
                new ObjectParameter("sta_id", sta_id) :
                new ObjectParameter("sta_id", typeof(long));
    
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_StatesSelect_Result>("usp_StatesSelect", sta_idParameter, con_idParameter);
        }
    
        public virtual ObjectResult<usp_StatesUpdate_Result> usp_StatesUpdate(Nullable<long> sta_id, string sta_name, Nullable<long> con_id)
        {
            var sta_idParameter = sta_id.HasValue ?
                new ObjectParameter("sta_id", sta_id) :
                new ObjectParameter("sta_id", typeof(long));
    
            var sta_nameParameter = sta_name != null ?
                new ObjectParameter("sta_name", sta_name) :
                new ObjectParameter("sta_name", typeof(string));
    
            var con_idParameter = con_id.HasValue ?
                new ObjectParameter("con_id", con_id) :
                new ObjectParameter("con_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_StatesUpdate_Result>("usp_StatesUpdate", sta_idParameter, sta_nameParameter, con_idParameter);
        }
    
        public virtual int usp_usersDelete(Nullable<long> users_id)
        {
            var users_idParameter = users_id.HasValue ?
                new ObjectParameter("users_id", users_id) :
                new ObjectParameter("users_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_usersDelete", users_idParameter);
        }
    
        public virtual ObjectResult<usp_usersInsert_Result> usp_usersInsert(string users_name, string users_password, string users_question, string users_answer, string users_email, string users_phone, Nullable<long> ut_id, Nullable<long> com_id)
        {
            var users_nameParameter = users_name != null ?
                new ObjectParameter("users_name", users_name) :
                new ObjectParameter("users_name", typeof(string));
    
            var users_passwordParameter = users_password != null ?
                new ObjectParameter("users_password", users_password) :
                new ObjectParameter("users_password", typeof(string));
    
            var users_questionParameter = users_question != null ?
                new ObjectParameter("users_question", users_question) :
                new ObjectParameter("users_question", typeof(string));
    
            var users_answerParameter = users_answer != null ?
                new ObjectParameter("users_answer", users_answer) :
                new ObjectParameter("users_answer", typeof(string));
    
            var users_emailParameter = users_email != null ?
                new ObjectParameter("users_email", users_email) :
                new ObjectParameter("users_email", typeof(string));
    
            var users_phoneParameter = users_phone != null ?
                new ObjectParameter("users_phone", users_phone) :
                new ObjectParameter("users_phone", typeof(string));
    
            var ut_idParameter = ut_id.HasValue ?
                new ObjectParameter("ut_id", ut_id) :
                new ObjectParameter("ut_id", typeof(long));
    
            var com_idParameter = com_id.HasValue ?
                new ObjectParameter("com_id", com_id) :
                new ObjectParameter("com_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_usersInsert_Result>("usp_usersInsert", users_nameParameter, users_passwordParameter, users_questionParameter, users_answerParameter, users_emailParameter, users_phoneParameter, ut_idParameter, com_idParameter);
        }
    
        public virtual ObjectResult<usp_usersSelect_Result> usp_usersSelect(Nullable<long> users_id)
        {
            var users_idParameter = users_id.HasValue ?
                new ObjectParameter("users_id", users_id) :
                new ObjectParameter("users_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_usersSelect_Result>("usp_usersSelect", users_idParameter);
        }
    
        public virtual ObjectResult<usp_usersUpdate_Result> usp_usersUpdate(Nullable<long> users_id, string users_name, string users_password, string users_question, string users_answer, string users_email, string users_phone, Nullable<long> ut_id, Nullable<long> com_id)
        {
            var users_idParameter = users_id.HasValue ?
                new ObjectParameter("users_id", users_id) :
                new ObjectParameter("users_id", typeof(long));
    
            var users_nameParameter = users_name != null ?
                new ObjectParameter("users_name", users_name) :
                new ObjectParameter("users_name", typeof(string));
    
            var users_passwordParameter = users_password != null ?
                new ObjectParameter("users_password", users_password) :
                new ObjectParameter("users_password", typeof(string));
    
            var users_questionParameter = users_question != null ?
                new ObjectParameter("users_question", users_question) :
                new ObjectParameter("users_question", typeof(string));
    
            var users_answerParameter = users_answer != null ?
                new ObjectParameter("users_answer", users_answer) :
                new ObjectParameter("users_answer", typeof(string));
    
            var users_emailParameter = users_email != null ?
                new ObjectParameter("users_email", users_email) :
                new ObjectParameter("users_email", typeof(string));
    
            var users_phoneParameter = users_phone != null ?
                new ObjectParameter("users_phone", users_phone) :
                new ObjectParameter("users_phone", typeof(string));
    
            var ut_idParameter = ut_id.HasValue ?
                new ObjectParameter("ut_id", ut_id) :
                new ObjectParameter("ut_id", typeof(long));
    
            var com_idParameter = com_id.HasValue ?
                new ObjectParameter("com_id", com_id) :
                new ObjectParameter("com_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_usersUpdate_Result>("usp_usersUpdate", users_idParameter, users_nameParameter, users_passwordParameter, users_questionParameter, users_answerParameter, users_emailParameter, users_phoneParameter, ut_idParameter, com_idParameter);
        }
    
        public virtual int usp_UserTypeDelete(Nullable<long> ut_id)
        {
            var ut_idParameter = ut_id.HasValue ?
                new ObjectParameter("ut_id", ut_id) :
                new ObjectParameter("ut_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UserTypeDelete", ut_idParameter);
        }
    
        public virtual ObjectResult<usp_UserTypeInsert_Result> usp_UserTypeInsert(string ut_code, string ut_name, Nullable<long> com_id)
        {
            var ut_codeParameter = ut_code != null ?
                new ObjectParameter("ut_code", ut_code) :
                new ObjectParameter("ut_code", typeof(string));
    
            var ut_nameParameter = ut_name != null ?
                new ObjectParameter("ut_name", ut_name) :
                new ObjectParameter("ut_name", typeof(string));
    
            var com_idParameter = com_id.HasValue ?
                new ObjectParameter("com_id", com_id) :
                new ObjectParameter("com_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UserTypeInsert_Result>("usp_UserTypeInsert", ut_codeParameter, ut_nameParameter, com_idParameter);
        }
    
        public virtual ObjectResult<usp_UserTypeSelect_Result> usp_UserTypeSelect(Nullable<long> ut_id)
        {
            var ut_idParameter = ut_id.HasValue ?
                new ObjectParameter("ut_id", ut_id) :
                new ObjectParameter("ut_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UserTypeSelect_Result>("usp_UserTypeSelect", ut_idParameter);
        }
    
        public virtual ObjectResult<usp_UserTypeUpdate_Result> usp_UserTypeUpdate(Nullable<long> ut_id, string ut_code, string ut_name, Nullable<long> com_id)
        {
            var ut_idParameter = ut_id.HasValue ?
                new ObjectParameter("ut_id", ut_id) :
                new ObjectParameter("ut_id", typeof(long));
    
            var ut_codeParameter = ut_code != null ?
                new ObjectParameter("ut_code", ut_code) :
                new ObjectParameter("ut_code", typeof(string));
    
            var ut_nameParameter = ut_name != null ?
                new ObjectParameter("ut_name", ut_name) :
                new ObjectParameter("ut_name", typeof(string));
    
            var com_idParameter = com_id.HasValue ?
                new ObjectParameter("com_id", com_id) :
                new ObjectParameter("com_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UserTypeUpdate_Result>("usp_UserTypeUpdate", ut_idParameter, ut_codeParameter, ut_nameParameter, com_idParameter);
        }
    }
}
