//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public long mem_id { get; set; }
        public Nullable<long> mt_id { get; set; }
        public Nullable<long> bt_id { get; set; }
        public string mem_name { get; set; }
        public string mem_companyname { get; set; }
        public string mem_owner { get; set; }
        public string mem_address1 { get; set; }
        public string mem_address2 { get; set; }
        public string mem_offaddress1 { get; set; }
        public string mem_offaddress2 { get; set; }
        public Nullable<long> city_id { get; set; }
        public Nullable<long> sta_id { get; set; }
        public Nullable<long> con_id { get; set; }
        public string mem_pincode { get; set; }
        public string mem_mobile { get; set; }
        public string mem_phone { get; set; }
        public string mem_offphone { get; set; }
        public string mem_email { get; set; }
        public string mem_webbsite { get; set; }
        public string mem_gstno { get; set; }
        public string mem_panno { get; set; }
        public string mem_logo { get; set; }
        public Nullable<System.DateTime> mem_cdate { get; set; }
        public Nullable<System.DateTime> mem_mdate { get; set; }
        public Nullable<long> mem_cid { get; set; }
        public Nullable<long> mem_mid { get; set; }
    
        public virtual BusinessType BusinessType { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual MemberType MemberType { get; set; }
        public virtual State State { get; set; }
    }
}
