//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class module
    {
        public module()
        {
            this.farms = new HashSet<farm>();
        }
    
        public long module_id { get; set; }
        public string module_name { get; set; }
    
        public virtual ICollection<farm> farms { get; set; }
    }
}
