//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.BusinessTypes = new HashSet<BusinessType>();
            this.BusinessTypes1 = new HashSet<BusinessType>();
            this.Members = new HashSet<Member>();
            this.Members1 = new HashSet<Member>();
            this.MemberTypes = new HashSet<MemberType>();
            this.MemberTypes1 = new HashSet<MemberType>();
        }
    
        public long users_id { get; set; }
        public string users_name { get; set; }
        public string users_password { get; set; }
        public string users_question { get; set; }
        public string users_answer { get; set; }
        public string users_email { get; set; }
        public string users_phone { get; set; }
        public Nullable<long> ut_id { get; set; }
        public Nullable<long> com_id { get; set; }
    
        public virtual ICollection<BusinessType> BusinessTypes { get; set; }
        public virtual ICollection<BusinessType> BusinessTypes1 { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Member> Members { get; set; }
        public virtual ICollection<Member> Members1 { get; set; }
        public virtual ICollection<MemberType> MemberTypes { get; set; }
        public virtual ICollection<MemberType> MemberTypes1 { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
